"""The engine's own lines, generated by tools/sync_engine_lines.py.

Do not edit by hand: re-run the sync against Rana's repo instead, so the
texts stay word for word what his engine speaks.

Source: keepalive-rana @ server/agents/safety_coach/protocols.py, server/agents/companion/micro_qa_engine.py
Synced: 2026-09-21
"""

ENGINE_LINES = [
    {
        "id": 'cpr_adult_step1_call911',
        "priority": 'normal',
        "text": "Don't panic. 911 CAD dispatch has been alerted with your exact GPS location. We need to start CPR immediately! Lay them flat on firm ground.",
    },
    {
        "id": 'cpr_adult_step2_posture',
        "priority": 'normal',
        "text": 'Put heel of hand on center of chest, lock your elbows straight.',
    },
    {
        "id": 'cpr_adult_step3_compressions',
        "priority": 'normal',
        "text": 'Ready: 3... 2... 1... PUSH! Push hard and fast to the beat! Push down two inches, let the chest rise fully every time.',
    },
    {
        "id": 'cpr_child_step1_call911',
        "priority": 'normal',
        "text": "Don't panic. 911 CAD dispatch has been alerted with your exact GPS location. We need to start CPR immediately! Lay them flat on firm ground.",
    },
    {
        "id": 'cpr_child_step2_posture',
        "priority": 'normal',
        "text": 'Use one or two hands on center of chest, lock elbows straight.',
    },
    {
        "id": 'cpr_child_step3_compressions',
        "priority": 'normal',
        "text": 'Compress to the beat! 30 compressions followed by 2 gentle breaths.',
    },
    {
        "id": 'cpr_infant_step1_call911',
        "priority": 'normal',
        "text": "Don't panic. 911 CAD dispatch has been alerted with your exact GPS location. We need to start CPR immediately! Place infant on a flat surface.",
    },
    {
        "id": 'cpr_infant_step2_posture',
        "priority": 'normal',
        "text": 'Place infant on flat surface. Use two fingers in center of chest.',
    },
    {
        "id": 'cpr_infant_step3_compressions',
        "priority": 'normal',
        "text": 'Compress gently 1.5 inches deep at 110 BPM. 30 compressions then 2 gentle puffs.',
    },
    {
        "id": 'choke_adult_step1_assess',
        "priority": 'normal',
        "text": 'Call 911 immediately! Ask: Are you choking? Can you speak?',
    },
    {
        "id": 'choke_adult_step2_heimlich',
        "priority": 'normal',
        "text": 'Stand behind them. Make a fist above navel, pull sharply inward and upward.',
    },
    {
        "id": 'choke_child_step1_assess',
        "priority": 'normal',
        "text": 'Call 911 immediately on speaker! Kneel behind child, encourage them to cough.',
    },
    {
        "id": 'choke_child_step2_thrusts',
        "priority": 'normal',
        "text": 'Kneel behind child. Make a fist above navel, give quick upward thrusts.',
    },
    {
        "id": 'choke_infant_step1_call911',
        "priority": 'normal',
        "text": 'Call 911 on speaker! Never do a blind finger sweep.',
    },
    {
        "id": 'choke_infant_step2_slaps',
        "priority": 'normal',
        "text": 'Lay infant face down along forearm. Give 5 firm back slaps, then turn over for 5 chest thrusts.',
    },
    {
        "id": 'bleed_step1_pressure',
        "priority": 'normal',
        "text": 'Call 911 on speaker! Apply heavy direct pressure on the wound now.',
    },
    {
        "id": 'bleed_step2_tourniquet',
        "priority": 'normal',
        "text": 'Apply tourniquet two to three inches above wound, tighten until bleeding stops.',
    },
    {
        "id": 'anaph_step1_epipen',
        "priority": 'normal',
        "text": 'Call 911 now! Locate the EpiPen immediately.',
    },
    {
        "id": 'anaph_step2_inject',
        "priority": 'normal',
        "text": 'Inject into outer mid-thigh, push until it clicks, hold for three full seconds.',
    },
    {
        "id": 'od_step1_narcan',
        "priority": 'normal',
        "text": 'Call 911 on speaker! Grab Narcan or Naloxone nasal spray.',
    },
    {
        "id": 'od_step2_administer',
        "priority": 'normal',
        "text": 'Spray full dose into one nostril. Place in recovery position.',
    },
    {
        "id": 'qa_agent_identity',
        "priority": 'response',
        "text": 'I am Agent 3, right here with you. Tell me what is happening or ask anything.',
    },
    {
        "id": 'qa_help_general',
        "priority": 'response',
        "text": 'I am right here with you. Tell me what happened—are they awake and breathing?',
    },
    {
        "id": 'qa_good_samaritan_legal',
        "priority": 'response',
        "text": 'Good Samaritan laws protect you. You are legally protected when attempting emergency CPR.',
    },
    {
        "id": 'qa_rib_cracking',
        "priority": 'response',
        "text": 'A rib pop can happen during effective CPR. Do not stop. Keep pushing to the beat.',
    },
    {
        "id": 'qa_technique_verification',
        "priority": 'response',
        "text": 'You are doing great. Keep hands centered, elbows locked, and push to the beat.',
    },
    {
        "id": 'qa_what_to_do_next',
        "priority": 'response',
        "text": 'Keep doing chest compressions in center of chest. Focus on the 110 beat.',
    },
    {
        "id": 'qa_confusion_guidance',
        "priority": 'response',
        "text": 'Stay calm, I am guiding you. Hands in center of chest, lock elbows, and push to the beat.',
    },
    {
        "id": 'qa_patient_alive_doubt',
        "priority": 'response',
        "text": 'Do not give up. Compressions are pumping oxygen to their brain right now. Keep pushing.',
    },
    {
        "id": 'qa_blood_fluid',
        "priority": 'response',
        "text": 'Wipe blood quickly from mouth, then continue chest compressions immediately without stopping.',
    },
    {
        "id": 'qa_hand_placement',
        "priority": 'response',
        "text": 'Heel of your hand right in center of chest between nipples. Lock elbows straight.',
    },
    {
        "id": 'qa_mouth_to_mouth',
        "priority": 'response',
        "text": 'Hands-only CPR is just as effective for adults. Keep pushing continuously to the beat.',
    },
    {
        "id": 'qa_exhaustion_stopping',
        "priority": 'response',
        "text": 'Do not stop compressions. If another person is with you, swap rescuers without pausing.',
    },
    {
        "id": 'qa_vomit_airway',
        "priority": 'response',
        "text": 'Roll them onto their side quickly to clear mouth, then return to back immediately.',
    },
    {
        "id": 'qa_aed_wet_surface',
        "priority": 'response',
        "text": 'Dry victim chest with a towel or shirt before applying AED pads. It is safe.',
    },
    {
        "id": 'qa_aed_pacemaker',
        "priority": 'response',
        "text": 'Place AED pad at least one inch away from visible pacemaker lump. Continue CPR.',
    },
    {
        "id": 'qa_checking_pulse',
        "priority": 'response',
        "text": 'Do not waste time checking pulse. If unresponsive and not breathing, continue CPR immediately.',
    },
    {
        "id": 'qa_tourniquet_pain',
        "priority": 'response',
        "text": 'Tourniquets must hurt to work. Tighten until bright red spurting bleeding stops completely.',
    },
    {
        "id": 'qa_expose_bare_chest',
        "priority": 'response',
        "text": 'Expose the bare chest immediately so you can see where to place your hands.',
    },
    {
        "id": 'qa_untrained_novice',
        "priority": 'response',
        "text": "Don't panic, I will guide you. Heel on center of chest, lock elbows, and push to the beat.",
    },
    {
        "id": 'qa_too_late_doubt',
        "priority": 'response',
        "text": 'Start compressions immediately. It is never too late to try to save their life.',
    },
    {
        "id": 'qa_patient_moan_sound',
        "priority": 'response',
        "text": 'Do not stop unless they push your hands away and breathe normally. Keep pushing.',
    },
    {
        "id": 'qa_agonal_breathing_sound',
        "priority": 'response',
        "text": 'Do not stop. Gasping is agonal breathing, not normal breathing. Keep pushing to the beat.',
    },
    {
        "id": 'qa_paramedic_arrival_debrief',
        "priority": 'response',
        "text": 'The paramedics are in charge now. Step back and take a deep breath. You did everything right.',
    },
    {
        "id": 'qa_ambulance_dispatch_status',
        "priority": 'response',
        "text": '911 CAD dispatch has been alerted with your exact GPS location. Keep pushing hard.',
    },
    {
        "id": 'qa_pressing_force',
        "priority": 'response',
        "text": 'Pushing at least two inches deep is necessary to pump blood. Keep pushing hard.',
    },
]
