#!/usr/bin/env python3
"""Read every line the engine speaks out of Rana's repo, into one render list.

His protocol library already names each line (`audio_cue_id`) and holds the exact
words (`spoken_voice_text`); the companion's offline answers sit in the micro-Q&A
engine. Parsing them beats copying by hand: the echo filter compares texts word
for word, so a typo is a bug, and re-running this after he edits a line shows
exactly what changed.

    python3 tools/sync_engine_lines.py ../keepalive           # writes tools/engine_lines.py
    python3 tools/sync_engine_lines.py ../keepalive --check    # only report drift

`render_directives.py` picks the result up automatically.
"""

import argparse
import ast
import datetime as dt
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent / "engine_lines.py"
PROTOCOLS = Path("server/agents/safety_coach/protocols.py")
MICRO_QA = Path("server/agents/companion/micro_qa_engine.py")


def literal(node) -> str | None:
    """The string value of an AST node, if it is a plain literal."""
    try:
        value = ast.literal_eval(node)
    except (ValueError, SyntaxError):
        return None
    return value if isinstance(value, str) else None


def directives(path: Path) -> list[dict]:
    """Every DirectiveStep(...) in the protocol library."""
    tree = ast.parse(path.read_text())
    found = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Call) and getattr(node.func, "id", "") == "DirectiveStep"):
            continue
        kw = {k.arg: k.value for k in node.keywords}
        cue, text = literal(kw.get("audio_cue_id")), literal(kw.get("spoken_voice_text"))
        if cue and text:
            found.append({"id": cue, "text": text, "priority": "normal",
                          "bpm": literal(kw.get("target_metronome_bpm")) or 0})
    return found


def answers(path: Path) -> list[dict]:
    """Every entry of the offline micro-Q&A table."""
    tree = ast.parse(path.read_text())
    found = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Dict):
            continue
        entry = {literal(k): v for k, v in zip(node.keys, node.values) if literal(k)}
        qid, answer = entry.get("id"), entry.get("answer")
        if qid is None or answer is None:
            continue
        qid, answer = literal(qid), literal(answer)
        if qid and answer:
            found.append({"id": f"qa_{qid}", "text": answer, "priority": "response"})
    return found


def render_module(lines: list[dict], source: str) -> str:
    body = [
        '"""The engine\'s own lines, generated by tools/sync_engine_lines.py.',
        "",
        "Do not edit by hand: re-run the sync against Rana's repo instead, so the",
        "texts stay word for word what his engine speaks.",
        "",
        f"Source: {source}",
        f"Synced: {dt.date.today().isoformat()}",
        '"""',
        "",
        "ENGINE_LINES = [",
    ]
    for line in lines:
        body.append("    {")
        body.append(f'        "id": {line["id"]!r},')
        body.append(f'        "priority": {line["priority"]!r},')
        body.append(f'        "text": {line["text"]!r},')
        body.append("    },")
    body.append("]")
    return "\n".join(body) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("repo", type=Path, help="checkout of the team repo")
    ap.add_argument("--check", action="store_true",
                    help="report what would change, write nothing")
    args = ap.parse_args()

    missing = [p for p in (PROTOCOLS, MICRO_QA) if not (args.repo / p).exists()]
    if missing:
        print(f"not a keepalive checkout: {args.repo} (missing {missing[0]})", file=sys.stderr)
        return 1

    lines = directives(args.repo / PROTOCOLS) + answers(args.repo / MICRO_QA)

    seen, unique = set(), []
    for line in lines:                      # the same line is reused across protocols
        if line["id"] in seen:
            continue
        seen.add(line["id"])
        unique.append(line)

    old = {}
    if OUT.exists():
        ns: dict = {}
        exec(compile(OUT.read_text(), str(OUT), "exec"), ns)      # noqa: S102 — our own file
        old = {line["id"]: line["text"] for line in ns.get("ENGINE_LINES", [])}

    new_ids = [l["id"] for l in unique if l["id"] not in old]
    changed = [l["id"] for l in unique if l["id"] in old and old[l["id"]] != l["text"]]
    gone = [i for i in old if i not in seen]

    print(f"{len(unique)} lines in the engine "
          f"({len(new_ids)} new, {len(changed)} reworded, {len(gone)} dropped)")
    for cid in changed:
        print(f"\n  REWORDED {cid}\n    was: {old[cid]}\n    now: "
              f"{next(l['text'] for l in unique if l['id'] == cid)}")
    for cid in new_ids:
        print(f"  new      {cid}")
    for cid in gone:
        print(f"  dropped  {cid}")

    if args.check:
        return 1 if (new_ids or changed or gone) else 0

    OUT.write_text(render_module(unique, f"{args.repo.name} @ {PROTOCOLS}, {MICRO_QA}"))
    print(f"\nwrote {OUT.relative_to(Path.cwd())}")
    if new_ids or changed:
        ids = " ".join(new_ids + changed)
        print("\nRender the clips that need a take:")
        print(f"  python3 tools/render_directives.py render "
              f"--voice-id EXAVITQu4vr4xnSDxMaL --only {ids}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
